let handler = async (m, { conn, text, usedPrefix, command }) => {
  let res = await (
    await fetch(
      `https://raw.githubusercontent.com/KazukoGans/database/main/anime/${command}.json`,
    )
  ).json();
  let cita = res[Math.floor(Math.random() * res.length)];
  conn.sendButton(
    m.chat,
    [
      ["NEXT IMAGE", `${usedPrefix + command}`],
      ["BACK TO MENU", ".menu"],
    ],
    m,
    {
      body: "*• Result From :* " + command,
      url: cita,
    },
  );
};
handler.help = [
  "akira",
  "akiyama",
  "asuna",
  "ayuzawa",
  "boruto",
  "chitanda",
  "chitoge",
  "deidara",
  "doraemon",
  "elaina",
  "emilia",
  "asuna",
  "erza",
  "gremory",
  "hestia",
  "hinata",
  "inori",
  "itachi",
  "isuzu",
  "itori",
  "kaga",
  "kagura",
  "kakasih",
  "kaori",
  "kaneki",
  "kosaki",
  "kotori",
  "kuriyama",
  "kuroha",
  "kurumi",
  "madara",
  "mikasa",
  "miku",
  "minato",
  "naruto",
  "natsukawa",
  "nekohime",
  "nezuko",
  "nishimiya",
  "onepiece",
  "pokemon",
  "rem",
  "rize",
  "sagiri",
  "sakura",
  "sasuke",
  "shina",
  "shinka",
  "shizuka",
  "shota",
  "tomori",
  "toukachan",
  "tsunade",
  "yatogami",
  "yuki",
].map((a) => a + " *[random image]*");
handler.tags = ["anime"];
handler.command = [
  "akira",
  "akiyama",
  "asuna",
  "ayuzawa",
  "boruto",
  "chitanda",
  "chitoge",
  "deidara",
  "doraemon",
  "elaina",
  "emilia",
  "asuna",
  "erza",
  "gremory",
  "hestia",
  "hinata",
  "inori",
  "itachi",
  "isuzu",
  "itori",
  "kaga",
  "kagura",
  "kakasih",
  "kaori",
  "kaneki",
  "kosaki",
  "kotori",
  "kuriyama",
  "kuroha",
  "kurumi",
  "madara",
  "mikasa",
  "miku",
  "minato",
  "naruto",
  "natsukawa",
  "nekohime",
  "nezuko",
  "nishimiya",
  "onepiece",
  "pokemon",
  "rem",
  "rize",
  "sagiri",
  "sakura",
  "sasuke",
  "shina",
  "shinka",
  "shizuka",
  "shota",
  "tomori",
  "toukachan",
  "tsunade",
  "yatogami",
  "yuki",
];
handler.limit = true;

module.exports = handler;
